### ISSUE TITLE
[IOS] onRegionChangeComplete in setState make map move continuesly

### ISSUE THREAD

**Issue by jihokim2** [react-native-community/react-native-maps#1966]
react-native: 0.51.0
    react: 16.0.0
    react-native-maps: 0.19.0 

Hi I found bug setState is called continueosly

I want to put in setState in onRegionChangeComplete. But map moves continuously . So I can't control the map.

Here Is the Sample Code. Please fix this problem.

<MapView
  style={{
      height: 500,
      width: 500,
      alignItems: 'center'
  }}
  region={this.state.region}
  provider={PROVIDER_GOOGLE}

  onRegionChangeComplete={(region) => {
          this.setState({
              isSpinnerShow: false
          });
      }
  }
  ref = {(ref)=> this.mapView=ref}

>
</MapView>

**Comment by jihokim2** [comment]
This below code operate normally. I think google map run abnormally. Please fix this issue. 
<MapView
  style={{
      height: 500,
      width: 500,
      alignItems: 'center'
  }}
  region={this.state.region}
 //provider={PROVIDER_GOOGLE} <= I think this link makes issue
  onRegionChangeComplete={(region) => {
          this.setState({
              isSpinnerShow: false
          });
      }
  }
  ref = {(ref)=> this.mapView=ref}

>
</MapView>

**Comment by rborn** [comment]
@jihokim2 it looks like google maps is adjusting internally the position all the time, so it will trigger this crazy loop as long as you set the state in onRegionChangeComplete.

**Comment by jihokim2** [comment]
But In react-native-maps: 0.18.3, it does't happen. Does google maps upgrade make the problem? @rborn

**Comment by rborn** [comment]
@jihokim2 might be that

**Comment by jihokim2** [comment]
@rborn Thank you for your answer. If you fix this problem, notice me plz.

**Comment by harrymash2006** [comment]
I am also having the continuous map movement as I have onregionchange method. After I zoom in-out or change drag the map onregionchange gets called again and again in a loop while blocking other UI components on the screen. Any suggestions on how to fix it?

**Comment by alvelig** [comment]
I only can recommend not to use state-managed region. I experienced some choppy behavior if move the map many times.

But please, make it according to the template. We need a reproducible example and ideally a gif or a video of this problem. Then we could find a resolution for your problem

**Comment by voratham** [comment]
I have problem same as everybody. 

I try record gif video by after reload  my map component will  movement automatic
as if someone drag map

i have attach gif
https://im4.ezgif.com/tmp/ezgif-4-b014241701.gif

`
import React, { Component } from 'react';
import {  StyleSheet, View,Text , Dimensions , TouchableOpacity } from 'react-native';
import MapView from 'react-native-maps';
const { width, height } = Dimensions.get("window");

// Google Map
const ASPECT_RATIO = width / height;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = ASPECT_RATIO * LATITUDE_DELTA

	var driverMovement = [
				{   _id : "01",
                    latitude:13.628235,
                    longitude:100.626800
                },
                {
                    _id : "02",
                    latitude:13.624510,
                    longitude:100.625154

                },
                {
                    _id : "03",
                    latitude:13.622022,
                    longitude:100.623996

                },
                {
                    _id : "04",
                    latitude:13.619623,
                    longitude: 100.622807
                },
                {
                    _id : "05",
                    latitude:13.621696,
                    longitude:100.623741
                },
                {

                    _id : "011",
                    latitude:13.619812,
                    longitude:100.622802
                },  
                {
                    _id : "012",
                    latitude:13.619931,
                    longitude:100.623124
                }, 
                 {
                    _id : "013",
                    latitude:13.619964,
                    longitude:100.623198
                }
   	 ];





class  MapContainer extends Component {

	constructor(props) {
	  super(props);
	
	  this.state = {  
	  		indexMarker : {
	  			start : 0 ,
	  			end  : 1
	  		},
	  		 region: {
		      latitude: 13.627235,
		      longitude: 100.626800,
		      latitudeDelta: 0.0922,
		      longitudeDelta: 0.0421,
		    },
		    marker :[	{   _id : "01",
                    latitude:13.628235,
                    longitude:100.626800
                }],
		    latlng : {
		    	latitude : 13.627235,
		    	longitude :100.626800
		    }

		};
	}
		
		_updateMarker(){
			if(this.state.marker.length >= driverMovement.length) return console.log('marker has been')
			console.log('driver :: ' , driverMovement.slice(this.state.indexMarker.end , this.state.indexMarker.end+1))
			this.setState({
				marker : driverMovement.slice( 0, this.state.indexMarker.end+1),
			  	indexMarker : { start : this.state.indexMarker.end , end :this.state.indexMarker.end+1    },
			})

		}

		onRegionChange(region) {
		  this.setState({ region });
		}

		render() {
		  return (
		  	<View style={{flex:1}}>
		  	  	<MapView
		  	  		style={{flex:1}}
		  	  			provider={MapView.PROVIDER_GOOGLE}
		      		region={this.state.region}
					onRegionChangeComplete={ this.onRegionChange.bind(this)}
		    	>
	
		


					{this.state.marker.map( (driver , index) => (
							<MapView.Marker
								key={index}
							  coordinate={{...driver}}
							/>

					))}



		    	</MapView>
		    	<Text>
		    		{JSON.stringify(this.state.indexMarker)}
		    	</Text>

		    	<Text>
		    		{JSON.stringify(this.state.marker)}
		    	</Text>
		    	<TouchableOpacity
	    			onPress={() => this._updateMarker()}
		    		 style={{backgroundColor:'red' , padding: 10 ,height:80 }}>
		    		
		    		<Text>Update</Text>	
		    	</TouchableOpacity>
		    </View>
		  );
		}
    
}

export default (MapContainer);`


my package json 
```
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "^0.19.0",
```

**Comment by harrymash2006** [comment]
@alvelig : Here is the video demonstrating the issue. 
https://www.dropbox.com/s/3d8izoi3mk5jdde/map_regionchangeissue.mp4?dl=0

I am doing no fancy thing in the code. I am just using this 

<MapView
                region={this.state.region}
                ref="map"
                onRegionChange={this.onRegionChange}
                provider={PROVIDER_GOOGLE}
                showsUserLocation = {true}
                style={[styles.map,{height: this.state.isCheckedIn ? '70%' : '100%'}]}

              >
and 

  onRegionChange(region) {
    this.setState({ region });
}

**Comment by rborn** [comment]
@harrymash2006 @voratham, you can either:
- wait for https://github.com/react-community/react-native-maps/pull/1953 to be merged, or use that fork.

for the current version:
- add this in your map ( it works for the current npm version, after we merge this shouldn't be necessary anymore)

```
    onMapReady = () => {
        Platform.OS === 'ios' && this.map.animateToRegion(initialRegion, 0.1); // TODO remove once the initialRegion is fixed in the module
    };
```

and as a general rule: 
- **don't set the region property at all (use initialRegion), and don't make it dependent of the state while the state is set by `onRegionChange`. It seems that the google maps is adjusting the position internally which triggers a change event -  so a loop will be created**

**Comment by harrymash2006** [comment]
@rborn : I don't understand this:
**don't set the region property at all (use initialRegion), and don't make it dependent of the state while the state is set by onRegionChange. It seems that the google maps is adjusting the position internally which triggers a change event - so a loop will be created**

don't use region property? You mean I should not use region={this.state.region} anymore and use initialregion? and don't make it dependent on state. Actually we don't use region property how can I update the region while users zoom-in/zoom-out the map and drags the map ? because I guess we have to do this 
onRegionChange(region) {
this.setState({ region });
}

to handle that no?

**Comment by rborn** [comment]
@harrymash2006  This is my map (partial code, it belongs to a component that takes care of the markers and so).

As you can see I only have the `initialRegion` set, and I don't set the region at all
`onMapReady` is there to overcome the bug fixed in the PR I was talking about.

Why do you need the region to be in the state? And even if you need it for other purposes, don't do `region={this.state.region}` To update the map (add markers, etc) use `onRegionChangeComplete` like below

 
~~~

    onRegionChangeComplete = region => {
        this.getUsersForMap(region);
    };

    onMapReady = () => {
        Platform.OS === 'ios' && this.map.animateToRegion(initialRegion, 0.1); // TODO remove once the initialRegion is fixed in the module
    };

<MapView
                        ref={map => {
                            this.map = map;
                        }}
                        provider={PROVIDER_GOOGLE}
                        style={styles.map}
                        onRegionChangeComplete={this.onRegionChangeComplete}
                        minZoomLevel={2}
                        maxZoomLevel={20}
                        rotateEnabled={false}
                        pitchEnabled={false}
                        showsUserLocation={true}
                        moveOnMarkerPress={false}
                        initialRegion={initialRegion}
                        onMapReady={this.onMapReady}
                    >
                    ...
~~~

**Comment by alvelig** [comment]
Yep, and if you need to force region, do `animateToRegion`

**Comment by harrymash2006** [comment]
@rborn @alvelig 
Hi guys,

Thank you so much for the help.

That new commit fixed the issue and using your suggestions I am now able to get the map thing working properly now.

This blue dot works perfectly and shows the exact user location. Just curious, is there any callback function to get the location of that blue dot(which shows user's current location) on the map?. Is that possible?
 
I am using navigator.geolocation.getCurrentPosition function to get current location but it returns not-so accurate location sometimes and fails miserably sometimes on Android too. Is there a workaround? Any suggestions?

**Comment by rborn** [comment]
@haikyuu maybe try with `navigator.geolocation.watchPosition` ? I think it will be more accurate but you might also need to call `getCurrentPosition` when you init the component.

**Comment by alvelig** [comment]
See here https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665 for the idea

**Comment by harrymash2006** [comment]
@rborn @alvelig 

Thank you so much guys. Your suggestions help me a lot to fix my map. Thanks again :)

**Comment by Agontuk** [comment]
@harrymash2006, about location failing on android, I just published a new package which uses Google Play Service's new `FusedLocationProviderClient` API for fetching location. It'll be really helpful if you try it out & give feedback if it improves location feature for your project. Also it has the exact same API as RN's geolocation API, so you can basically test it without changing any js code.

[https://github.com/Agontuk/react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service)

**Comment by Germanaz0** [comment]
I had the same problem but did a fast fix, is not perfect, but worked for me.

```typescript 
onRegionChange(region) {

      let distance = this.calculateDistance(region.latitude, this.props.region.latitude, region.longitude, this.props.region.longitude);
      
       if (distance > 0) {
           this.setState({status: this.state.status.setRegion(region)});
       }
}
```

And the function to calculate distance is:

```typescript
calculateDistance(lat1: number, lat2: number, long1: number, long2: number) {
   let p = 0.017453292519943295;    // Math.PI / 180
   let c = Math.cos;
   let a = 0.5 - c((lat1 - lat2) * p) / 2 + c(lat2 * p) * c((lat1) * p) * (1 - c(((long1 - long2) * p))) / 2;
   let dis = (12742 * Math.asin(Math.sqrt(a))); // 2 * R; R = 6371 km
   return dis;
}
```

**Comment by efkan** [comment]
I develop on Android and in my case, the issue about `onRegionChangeComplete` is that the event is fired multiple times. 

If I set map `ragion` among these two fired event `onRegionChangeComplete` event, the map is shown at the first and the last region consecutively.

And of course if the event is being reflected from Android completely, its mean that there is no many things to do to overcome this issue.

**Comment by asuri0n** [comment]
Same issue, juste remove `region={region}` in MapView

**Comment by abarisic86** [comment]
As mentioned in the issue #2503 above, I have this issue but just on notch-ed iPhones (iPhone X, iPhone Xr...)

**Comment by stan-sack** [comment]
Im seeing this behaviour in the simulator with every device type. I'm using `react-native@0.56.0` and `react-native-maps@0.21.0`. I switched `region={region}` to `initialRegion={region}` and it fixed it, but its basically a showstopper if you need to manipulate region :(

**Comment by dengue8830** [comment]
Problem
yes the problem occurs when making two fast map movements, the `onRegionChangeComplete` is called twice consecutively but as setstate is an async operation, when the first call sets the state it roll back the map to the previous position, then the second movement sets state to the latest position and that triggers a new `onRegionChangeComplete`, and so.

Solution
1) you could just remove the `region={state managed region}`
2) make a timeout to avoid extremely fast consecutive calls

I went for the 2) because i had to prevent unnecessarily calls to an API in `onRegionChangeComplete`. But technically just with option 2) you still can fall in the same problem but with much less probability. For  a complete solution you should implement both options.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by ciawalsh** [comment]
@rborn I am still getting this issue, even with the latest stable version of `react-native-maps`.

I have even tried adding a debounce method to the `onRegionChangeComplete` however it seems it only slows the map down from moving south on it's own.

One caveat though, this only happens on a physical device. Not a simulator through Xcode.

**Comment by rborn** [comment]
@ciawalsh are you managing the region in the state? 
aka : `map.region = this.state.region` ?  If yes, don't :)
Somehow the reported region by onRegionChangeComplete is different from the one you set and then you enter a loop

**Comment by ciawalsh** [comment]
@rborn - Ah yes I do. It's currently managed through state before I connect the component to redux. 

I shall move away from controlling the region through state in that case now. Thank you for getting back to me. If you hear nothing back from me, assume it has all gone well!

**Comment by elmotan95** [comment]
Hello guys, i still encounter this issue but this problem only happened on iPhone with notch only (X, XR, XS, XS Max). Android (with or without notch) and other iPhone don't have this problem. 
I'm using react native maps 0.24.2 and react native 0.59.8

Here's my code:
```javascript
          <MapView
            style={{ flex: 1 }}
            provider={PROVIDER_GOOGLE}
            onRegionChangeComplete={this.onRegionChange}
            region={this.state.region}
          />
```

I need to use state for managing region because i have text input to get coordinate by typing location. My temporary fix is by changing style to using device screen height - 150 and device screen width. 

Actually i want to use screen height - 100 (i have footer area and forced it to have 100 height) but it's still moving itself. I use @Germanaz0 method for calculating distance, it prevent the map to move but `onRegionChange` and `onRegionChangeComplete` still called.

**Comment by efecantekin** [comment]
> Hello guys, i still encounter this issue but this problem only happened on iPhone with notch only (X, XR, XS, XS Max). Android (with or without notch) and other iPhone don't have this problem.
> I'm using react native maps 0.24.2 and react native 0.59.8
> 
> Here's my code:
> 
> ```js
>           <MapView
>             style={{ flex: 1 }}
>             provider={PROVIDER_GOOGLE}
>             onRegionChangeComplete={this.onRegionChange}
>             region={this.state.region}
>           />
> ```
> 
> I need to use state for managing region because i have text input to get coordinate by typing location. My temporary fix is by changing style to using device screen height - 150 and device screen width.
> 
> Actually i want to use screen height - 100 (i have footer area and forced it to have 100 height) but it's still moving itself. I use @Germanaz0 method for calculating distance, it prevent the map to move but `onRegionChange` and `onRegionChangeComplete` still called.

I have same problem with same devices. Did you solve the problem?

`   <StyledMapView
              provider={PROVIDER_GOOGLE}
              followsUserLocation
              showsUserLocation={this.state.position !== undefined}
              showsCompass
              region={this.state.region}
            >`

**Comment by CristyTarantino** [comment]
This issue is still replicable. Did anybody solve the problem, apart from removing region?

**Comment by ghariosk** [comment]
For all those still struggling,  it seems this issue is happening when no other elements are present around the map and it is in full screen. It worked for me when I included a header to the otherwise full screen map. Strange ...

**Comment by tmtakashi** [comment]
hey, i was getting the same issue, but i just found out that it stops moving continuously when I wrap the `MapView` component with `SafeAreaView`.
My code looks like this.
```
<SafeAreaView style={styles.container}>
      <MapView
        style={styles.map}
        provider={PROVIDER_GOOGLE}
        region={region}
        onRegionChangeComplete={setRegion}
      />
    </SafeAreaView>
```
I might be a aesthetic compromise for some of you, but i hope that helps anyone.

**Comment by tomasswood** [comment]
> hey, i was getting the same issue, but i just found out that it stops moving continuously when I wrap the `MapView` component with `SafeAreaView`.
> My code looks like this.
> 
> ```
> <SafeAreaView style={styles.container}>
>     <MapView
>       style={styles.map}
>       provider={PROVIDER_GOOGLE}
>       region={region}
>       onRegionChangeComplete={setRegion}
>     />
> </SafeAreaView>
> ```
> 
> I might be a aesthetic compromise for some of you, but i hope that helps anyone.

This definitely solved my issue. As we are moving our app away from using the safeview, I managed to solve the issue and have the map full screen by doing the following:

```import { useSafeArea } from 'react-native-safe-area-context';

...

const insets = useSafeArea();
<View style={{ marginTop: -insets.top}}>
 <Map .../>
</View>
```

**Comment by RyanTG** [comment]
Our app experiences the issue that @dengue8830 described above:

> yes the problem occurs when making two fast map movements, the onRegionChangeComplete is called twice consecutively but as setstate is an async operation, when the first call sets the state it roll back the map to the previous position, then the second movement sets state to the latest position and that triggers a new onRegionChangeComplete, and so.

Is there simply a prop to disable the map from "centering" when `onRegionChangeComplete` is called? 

We don't need it to automatically center on the place where the map was when you stopped drag/panning for a split second, as it currently does. Not sure if there's something obvious we're missing. Thank you!

**Comment by AlanQuadros** [comment]
I just remove style={{...StyleSheet.absoluteFillObject}} from MapView and add style={{flex: 1}}

**Comment by bhomaramgtsinfo** [comment]
just remove region={region} in MapView and if you want to assign initial location/region then assign your region to initialRegion like initialRegion={this.state.region}. onRegionChangeComplete will stop to call again and again. Hope your issue will be resolved.
