### ISSUE TITLE
Android "elevation" style property doesn't work on map markers

### ISSUE THREAD

**Issue by benhoyt** [react-native-community/react-native-maps#224]
The React Native Android "elevation" style property (to raise a view and cast a native-looking shadow) does nothing for map markers -- is this because of the way markers are rendered as bitmaps on Android? Any way to work around it?

**Comment by luco** [comment]
+1 on this.

**Comment by Mrachko** [comment]
+1 on this too. It would be nice to implement this functionality, and it doesn't require a massive amount of changes (I think).

**Comment by HsanBenJobrane** [comment]
+1 on this

**Comment by juergengunz** [comment]
any workaround? (using images is not an option)

**Comment by tonygriv** [comment]
+1 on this

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by adimshev** [comment]
+1

**Comment by derrickbeining** [comment]
@christopherdro please reopen this issue because the issue is not resolved on the latest stable version (currently 0.23.0). Opening an new issue would only make this problem less visible for people searching for it on Google, etc.

**Comment by kosiakMD** [comment]
BTW: is it right next thing
Do Markers behave like they have `overflow = hidden`?
as to add a shadow in iOS I need to add additional View to wrap View with shadow

**Comment by Balasnest** [comment]
This is really needed things and its been 3 years this issue is in open state.
 
Is there any workaround?

**Comment by sobiso** [comment]
+1

**Comment by udielenberg** [comment]
+1

**Comment by antonioreyna** [comment]
looks like markers callouts have overflow hidden?

**Comment by oschade** [comment]
Please remove overflow hidden from markers.

**Comment by matiduarte** [comment]
+1

**Comment by Porisey** [comment]
+1

**Comment by moxorama** [comment]
You can use png with transparency as marker icon

**Comment by 7Style** [comment]
> You can use png with transparency as marker icon
PNG is not a solution. This leads to performance problems.

**Comment by DestroyeerU** [comment]
+1

**Comment by Eden-Eliel** [comment]
did people forget it?

**Comment by manishsainju** [comment]
+1

**Comment by Phantomo** [comment]
+1, open issue again please

**Comment by Sheharyar566** [comment]
Please open the issue again, as marker shadows are a nice feature to have.

**Comment by salah-ghanim** [comment]
I will lock this issue because there seem to be a big misunderstanding here as to what this library can and can't do.

The android google maps library doesn't use the native view system so introducing things that apply to the normal views like shadow is not possible out of the box. a feature request about this in google maps android sdk makes more sense than demanding it from this library.
