### ISSUE TITLE
Custom tile - add option for a function instead of a string for urlTemplate

### ISSUE THREAD

**Issue by compojoom** [react-native-community/react-native-maps#2283]
### Is this a bug report?
No, feature request

Right now the custom tile overlay:
```
<UrlTile
   /**
   * The url template of the tile server. The patterns {x} {y} {z} will be replaced at runtime
   * For example, http://c.tile.openstreetmap.org/{z}/{x}/{y}.png
   */
    urlTemplate={this.state.urlTemplate}
    /**
     * The maximum zoom level for this tile overlay. Corresponds to the maximumZ setting in
     * MKTileOverlay. iOS only.
     */
    maximumZ={19}
  />
```

expects a string for urlTemplate. Unfortunately not all tiles can be expressed with this. I'm trying to convert a sentinel hub example to react-native, but they are converting the x,y,z to a bounding box and I can't express this with urlTemplate. 

The javascript code for google maps api v3 is:
```
//Define custom WMS tiled layer
  var SHLayer = new google.maps.ImageMapType({
    getTileUrl: function (coord, zoom) {
      var proj = map.getProjection();
      var zfactor = Math.pow(2, zoom);
      // get Long Lat coordinates
      var top = proj.fromPointToLatLng(new google.maps.Point(coord.x * 512 / zfactor, coord.y * 512 / zfactor));
      var bot = proj.fromPointToLatLng(new google.maps.Point((coord.x + 1) * 512 / zfactor, (coord.y + 1) * 512 / zfactor));

      //create the Bounding box string
      var bbox =     (top.lng()) + "," +
        (bot.lat()) + "," +
        (bot.lng()) + "," +
        (top.lat());

      //base WMS URL
      var url = "https://services.sentinel-hub.com/ogc/wms/xxxx";
      url += "?REQUEST=GetMap"; //WMS operation
      url += "&SERVICE=WMS";    //WMS service
      url += "&VERSION=1.1.1";  //WMS version
      url += "&LAYERS=AGRICULTURE"; //WMS layers
      url += "&FORMAT=image/jpg" ; //WMS format
      url += "&SRS=EPSG:4326";     //set WGS84
      url += "&BBOX=" + bbox;      // set bounding box
      url += "&WIDTH=512";         //tile size in google
      url += "&HEIGHT=512";

      return url;                 // return URL for the tile

    },
    tileSize: new google.maps.Size(512, 512)
  });
```

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by compojoom** [comment]
@christopherdro - well problem still persist as one cannot use a function that returns a string for an URL... But ok.

**Comment by krisgerhard** [comment]
+1
