### ISSUE TITLE
Mapview leak memory on IOS

### ISSUE THREAD

**Issue by kduy969** [react-native-community/react-native-maps#2782]
Version: branch master, commit https://github.com/react-native-community/react-native-maps/commit/21a7536cb42ac793e744e75e0fb4f8422f601589
React native version: 0.59.1
Platform: IOS
Map Provider: Google.

Issue:
Each time I open a screen which contain a ```<MapView/> ```, memory go up about 50mb, but when I go back , memory not reduce the same amount ,try this a few times will make app crash. After that, I use Xcode profile tool to monitor leak event, this point out leak memory come from AIRGoogleMap[getActionForTarget] , despite I have no marker on MapView. When I remove ```<MapView/>``` from my screen, the issue gone away.

PS: I switch to master when trying to workaround a bug mentions here:
https://github.com/react-native-community/react-native-maps/issues/2737#issuecomment-478567956

**Comment by sinodko** [comment]
isn't this related to #2775 ?

**Comment by sinodko** [comment]
Anyway, I'm also encountering some weird behaviour on iOS... On Android, everything works just perfect and smooth (even on emulator device). But on iOS with iPhone XR (The fastest Apple Bionic A12 chip) and release build, react-navigation transition is very laggy when I'm entering or leaving Map Screen.

I don't know if this is problem of react-navigation or react-native-map,  but I'm using most current versions of react-native, react-native-maps and react-navigation.

**Comment by rborn** [comment]
@kduy969 thanks for this, please have a look at  #2775  (what @sinodko said) and see if the same case and maybe add your findings to it.

(it has more details and info so we'll switch to that issue for this bug)

**Comment by sinodko** [comment]
@rborn can this memory leak be also related to the problem that I'm encountering?

**Comment by rborn** [comment]
@sinodko it might be this only if the lag starts after you enter/leave the map multiple times ( and assuming the leak is not related to the tiles which would do show on zoom or region chnage)
If it happens right away I don't really know what's going on. 

Do you have this issue on any other device?

Maybe you're doing something fancy (like re-rendering multiple times or building stuff on an event that triggers often -  like onRegionChange) ?

**Comment by sinodko** [comment]
I'm making SQLite call on componentDidMount which is fetching markers (there can be even 500+ markers) so there is some heavy liftings. I will take a look at number of renders in the component but the weird thing is that on mid-upper range android device is everything working smoothly but on top level iOS flagship (in terms of processor and power) the transition is crispy. 

If I run SQLite query after transition is complete, then transition is more smooth. But then on "back" transition the performance is laggy again.

I will take a deeper look on that and if I'm not able to make it smooth I'll probably open new issue with additional info :)

**Comment by rborn** [comment]
500 markers? this is a lot

I'd suggest to implement some clustering and/or exclusion based on the zoom level and current region to reduce the number.

Can you try to use Instruments on the app maybe you find where the memory goes bonkers?

**Comment by sinodko** [comment]
I'm using the react-native-maps-super-cluster package for clustering and the performance on map is just fine even on old xperia Z2 during map moving/zooming. I'm even using onRegionChangeCompleted to recompute visible markers by viewport of the map widget - :) The problem only appears when I'm entering or leaving the map even when I open the Map which contains only 1 marker.

**Comment by rborn** [comment]
@sinodko apple map or google ? (maybe we can narrow the issue)

**Comment by sinodko** [comment]
@rborn Google Maps. I wanted to use AppleMaps but there was a problem with onRegionChangeCompleted firing while using custom tiles (only in offline mode) so I decided to go with Google Maps instead.

**Comment by ottoo** [comment]
Use https://github.com/react-native-community/react-native-maps/commit/558b34c9fd6d698a22dd016b635a602d488b4400 icon property on markers instead of the image property. This made a huge difference.

**Comment by kduy969** [comment]
@sinodko @rborn this may be same problem with #2775 , it's happen on Google Map too , the only difference is I don't have any marker on MapView. Every time I open screen with MapView , i see a leak memory event in Xcode profile tool, and the memory chart only going up after multiple open/close.

**Comment by sinodko** [comment]
@ottoo even when I'm using only default markers with their default look?

**Comment by ottoo** [comment]
> @ottoo even when I'm using only default markers with their default look?

No, we're using custom markers.

**Comment by rphlmr** [comment]
Same issue here, ram increase on ios every time I open a screen with a MapView (google provider). I'm using the master branch off react-native-maps to fix issues on Android graddle build.

**Comment by eyu0415** [comment]
Same issue here(google provider)
In my case,
react-native: 0.59.3
react-native-maps: "github:react-community/react-native-maps",

If I push the scene contain MapView, memory increased around 0.09GB.
and pop the scene the allocation was not freed.
If I push same scene again, memory increased again without.
[memory leak attachment](https://i.ibb.co/FJQ9hqZ/2019-04-08-3-01-20.png)
--

I solved this issue with react-native-maps: 0.23.0

[solved attachment](https://i.ibb.co/CBKN2yJ/2019-04-08-3-06-56.png)

**Comment by eyu0415** [comment]
> @eyu0415 can I use 0.23.0 with react-native 0.59.x?

Sure, I used react-native 0.59.3 & react-native-maps 0.23.0

**Comment by sinodko** [comment]
Memory leaks persist even with react-native-maps version 0.24.0

**Comment by jramalho** [comment]
> @sinodko For iOS only, I think. For android, no.

in Android too.
# #2807

**Comment by todtod80** [comment]
It's still occurring in `0.24.0`

**Comment by jacobklerfelt** [comment]
I experience the same issue. No problem with Apple Maps, but when switching provider to Google the RAM memory increases steadily until it reaches about 1,6gb and crashes application.

**Comment by ntelkedzhiev** [comment]
I have a similar behavior on Android.

Android: 9.0
react-native: 0.59.4
react-native-maps: 0.24.0

The app crashed once the MapView loads the actual map. I experience it on the emulator but not on a real device. Maybe the reason is that my emulator has less RAM.

**Comment by sinodko** [comment]
Hope this will get solution soon. Feeling so helpless because I can't even read Objective C 😄

**Comment by christopherdro** [comment]
I just published 0.24.1 with the following commit(90e4a6e3b12e21b92a635321e02f010693fca6cb) that should resolve the memory leak issue. Can you guys test and confirm?

**Comment by rphlmr** [comment]
@christopherdro Thanks for the commit.
I still have the issue with `"react-native-maps": "https://github.com/react-native-community/react-native-maps/archive/v0.24.1.tar.gz"` :(

**Comment by christopherdro** [comment]
@rphlmr Can you try and use the instruments took to see if you can confirm the issues are coming from this library?

**Comment by rphlmr** [comment]
@chrisknepper I'm totally new about that  😂
I don't know what i'm seeing, tell me if it's useless
<img width="1990" alt="Capture d’écran 2019-04-16 à 23 55 02" src="https://user-images.githubusercontent.com/20722140/56246904-7deb0200-60a3-11e9-8af9-cb9e439523d3.png">

**Comment by sinodko** [comment]
@christopherdro I can confirm that memory leak still persist on 0.24.1 patched version :( still around 150-200MB leak after every time that Google Map is opened on iOS.

**Comment by christopherdro** [comment]
Just published 0.24.2 with the following fix https://github.com/react-native-community/react-native-maps/pull/2818

**Comment by rphlmr** [comment]
@christopherdro @ukrbublik Thank you, it works !!!

**Comment by rborn** [comment]
closing as per https://github.com/react-native-community/react-native-maps/issues/2782#issuecomment-484147251
