### ISSUE TITLE
disable Marker Animation on IOS with PROVIDER_GOOGLE

### ISSUE THREAD

**Issue by arunpugahz** [react-native-community/react-native-maps#3290]
# Bug
When I move across Map and get new markers from API, the existing marker animates itself to its new coordinates even though I have not used any animation in my code.
I just want the markers to appear at new coordinates instead of moving around.
facing this issue only with PROVIDER_GOOGLE on iOS
how to disable this animation?

Library version: 0.26.1
```
<MapView
onRegionChangeComplete={this.regionChange}
provider={PROVIDER_GOOGLE}
>
{props.mapFeed.map(item =>
 return(
<Marker
          coordinate={{
            latitude: item.latitude,
            longitude: item.longitude,
          }}
          title={item.id}
          description={item.text}
        />
))}
</MapView>
```
![ezgif com-resize](https://user-images.githubusercontent.com/53349433/74517980-1e66b880-4f39-11ea-82e6-8867cf53e012.png)

**Comment by phbprogramming** [comment]
Same issue. I have a custom callout that appears, and when I tap on new points of interest, the callout slides across the map to the new location.

**Comment by rborn** [comment]
Closing as really old, please ping me if still an issue

**Comment by phbprogramming** [comment]
I never got the issue resolved. Is there another closed issue you could link if this is a repeat issue or something else?

**Comment by rborn** [comment]
@phbprogramming ok, re-opening it.

What I see missing from the above code is that there is no `key` nor `identifier` passed to the Marker. 
Passing a `key` that's unique for the marker should fix this. I suggest something like `key_${item.longitude}_${item.latitude}`
Otherwise the map will try to optimise the rendering and reuse them not to render again (which is more expensive than to animate)

**Comment by bzrncev** [comment]
@rborn I tried with unique identifier, and the issue still remains, the marker is animating. On Android is works as supposed.

**Comment by rborn** [comment]
@bzrncev tried with `key` ?

**Comment by bzrncev** [comment]
@rborn With key it works as supposed, maybe it should be included in documentation. If you need help, let me know and I will make a PR. Regards

**Comment by rborn** [comment]
Yes a PR would be great, thanks 😊

**Comment by SpQuyt** [comment]
I highly recommended that we should include this into docs. Because not everyone has time to search for issue which is really easy like this :(
