### ISSUE TITLE
useNativeDriver warning when using animated markers

### ISSUE THREAD

**Issue by liamlows** [react-native-community/react-native-maps#3483]
# Bug report

## Summary

When using React Native v0.62, a consistent warning will generate when using an animated region and animated marker. The warning (seen below) can be suppressed on iOS by setting the option `useNativeDriver: false`  in `AnimatedRegion.js`.

See https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated#how-do-i-use-this-in-my-app

## Environment info

`react-native info` output:

```bash
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
```

Library version: 0.27.1

## Steps to reproduce

1. Create an animated marker with a new AnimatedRegion and utilize as a coordinate on map

Describe what you expected to happen:
N/A

## Reproducible sample code

New animated region

```
coordinate: new AnimatedRegion({
        latitude: 37.785834,
        longitude: -122.406417,
        latitudeDelta: 0,
        longitudeDelta: 0
      })
```

JSX for Map...

```
        <MapView
          style={styles.map}
          showUserLocation
          followUserLocation
          loadingEnabled
          region={this.getMapRegion()}
        >
          <Marker.Animated
            ref={marker => {
              this.marker = marker;
            }}
            coordinate={this.state.coordinate}
          />
        </MapView>
```

**Comment by dl-husky73** [comment]
Any updates here?  I am having same issues...

**Comment by liamlows** [comment]
> Any updates here?  I am having same issues...


I submitted a PR to fix it but it seems to fail the ci checks because of a yarn issue. I'll try to fix and resubmit and hopefully they will merge. To fix it though take a look above where I mention how to suppress the warning/issue.

**Comment by liamlows** [comment]
fix was merged to master! 😄

**Comment by dl-husky73** [comment]
Awesome, thx!

**Comment by viscardo** [comment]
It is still not working for me using  "react-native": "~0.63.3", "react-native-maps": "^0.27.1"

**Comment by shoonne** [comment]
same for me, still getting this warning every second

**Comment by liamlows** [comment]
> same for me, still getting this warning every second

Take a look at my summary paragraph above, I explained how to suppress it by changing one line of code in the package's folder in node-modules.
