### ISSUE TITLE
Markers with custom Views are positioned above Callouts

### ISSUE THREAD

**Issue by deckchairlabs** [react-native-community/react-native-maps#418]
When rendering a relatively dense cluster of markers, tapping one to reveal the callout causes the custom markers to be displayed above the callout and it's contents.

Is there no way to change the zIndex of the markers?

**Comment by 1ne8ight7even** [comment]
Same problem here, but only on ios. Android is working fine.

**Comment by attila135786** [comment]
Is there any update on this? I'm seeing the same problem.

**Comment by chadwilken** [comment]
I am also seeing this issue on iOS. Running React Native 0.32.1 and react-native-maps 0.8.0.

**Comment by MadeInMoon** [comment]
Did someone succeeded to handle this problem?

**Comment by sandman45** [comment]
I see the same.. pretty annoying 
"react-native": "^0.41.2",
 "react-native-maps": "^0.13.0",

**Comment by maggialejandro** [comment]
This should solve the issue https://github.com/airbnb/react-native-maps/pull/1405

**Comment by alvelig** [comment]
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by sircEUNHO** [comment]
@alvelig This doesn't work for me. My react native maps version is 0.21.0 and the codes on the attempts to fixes are on the package. But callouts are still behind markers and weird thing is that when I click outside the callout, the callout goes in front of the marker. By the way, my markers are custom image markers.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by aitorct** [comment]
This is still happening. I've tried upgrading to the latest version of the library (0.26.1), no luck. The issue has not been solved yet.
